apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: name-pod
    spec:
      containers:
      - name: name
        image: arungupta/name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
