apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
      - name: webapp
        image: arungupta/webapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: GREETING_SERVICE_HOST
          value: "greeting-service"
        - name: GREETING_SERVICE_PORT
          value: "80"
        - name: GREETING_SERVICE_PATH
          value: "/resources/greeting"
        - name: NAME_SERVICE_HOST
          value: "name-service"
        - name: NAME_SERVICE_PORT
          value: "80"
        - name: NAME_SERVICE_PATH
          value: "/resources/names/1"
