AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Greeting Amazon API Gateway.
Resources:
  GreetingFunction:
    DependsOn:
      - PreTrafficLambdaFunction
      - PostTrafficLambdaFunction
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: org.aws.samples.compute.greeting.GreetingHandler::handleRequest
      Runtime: java8
      CodeUri: ../../../microservices-greeting/target/greeting.zip
      MemorySize: 1024
      Timeout: 20
      Tracing: Active
      AutoPublishAlias: prod
      DeploymentPreference:
        Enabled: true
        Type: Canary10Percent5Minutes
        Alarms:
          - Ref: LambdaAliasErrorMetricGreaterThanZeroAlarm
          - Ref: LambdaLatestVersionErrorMetricGreaterThanZeroAlarm
        Hooks:
          PreTraffic: !Ref PreTrafficLambdaFunction
          PostTraffic: !Ref PostTrafficLambdaFunction
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "ssm:PutParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/GreetingApiEndpoint"
      Events:
        greet:
          Type: Api
          Properties:
            Path: /resources/greeting
            Method: GET
            RestApiId: !Ref GreetingApi
  GreetingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: "2.0"
        paths:
          "/resources/greeting":
            get:
              responses:
                "200":
                  content:
                    text/plain:
                      scheme:
                        type: string
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GreetingFunction.Arn}/invocations"
  Parameter:
    Type: "AWS::SSM::Parameter"
    Properties: 
      Name: GreetingApiEndpoint
      Description: Greeting API Endpoint
      Type: String
      Value: !Sub '${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com'

  PreTrafficLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hooks/
      Handler: preTrafficHook.handler
      Runtime: nodejs6.10
      FunctionName: !Sub 'CodeDeployHook_gretting_preTrafficHook'
  PostTrafficLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hooks/
      Handler: preTrafficHook.handler
      Runtime: nodejs6.10
      FunctionName: !Sub 'CodeDeployHook_gretting_postTrafficHook'
  LambdaAliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Alias
          Value: !Ref GreetingFunction.Alias
        - Name: FunctionName
          Value: !Ref GreetingFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
  LambdaLatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Version
          Value: !Ref GreetingFunction.Version
        - Name: FunctionName
          Value: !Ref GreetingFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
Outputs:
  greetingApiEndpoint:
    Description: Greeting API URL for application
    Value: !Sub 'https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/prod/resources/greeting'
